name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Run tests with coverage
      run: cargo tarpaulin --verbose --out lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_ORG_TOKEN }}
        verbose: true
        fail_ci_if_error: true
